# step 1 tae no image insatll all the nessary dependencies
FROM node as Builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run prisma:generate || npx prisma generate

#step - 2 take a small image of node and build and npm the image
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app  ./
RUN npx prisma generate
EXPOSE 6500
CMD ["npm", "run", "dev"]
