FROM node:20-alpine
WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install

# copy source
COPY . .

ENV VITE_LOGIN_OAUTH_ID=413125396319-v8huk4u61jtntftqphh2bei37a1dkme2.apps.googleusercontent.com
ENV  VITE_BASE_URL=https://promanage.duckdns.org

# build production files
RUN npm run build

# serve with vite preview
EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
